spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hero-store
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
hibernate:
  id:
    new_generator_mappings: true

flyway:
  user: admin
  password: admin